---
title: "Conference Review: The 7th China R Conference"
author:
  - name: Jing Leng
    affiliation: University of Michigan
    address:
    - line 1
    - line 2
    email:  jing.leng@cos.name
  - name: Yihui Xie
    affiliation: RStudio, Inc
    address:
    - "2609 Ferndale Ave #9"
    - Ames, IA 50010, USA
    email:  yihui.xie@cos.name
output: rticles::rjournal_article
---

The 7th China R Conference (Beijing session) was held in Renmin University of China (RUC), Beijing, from May 24th to 25th, 2014. The conference was organized by Capital of Statistics (COS, http://cos.name), an online statistical community in China, together with the Center for Applied Statistics of RUC, the School of Statistics of RUC, and the Business Intelligence Research Center of Peking University. 

The China R Conference is the largest event for Chinese R users and developers. Every year, people from all over the country get together for R techniques, packages, applications, as well as topics on statistics and data analysis. This bi-annual event normally takes place in Beijing in summer and Shanghai in winter. More than 900 people attended the Beijing session this year, which included 33 talks, 6 lightening talks and one panel discussion. 

The conference was held in the Rulun Auditorium on the first day. There were 9 talks, followed by a panel discussion on the big data industry and education. The discussion panel included Kai Yu from Baidu Institute of Deep Learning, Hansheng Wang from Peking University, Xizhi Wu from Renmin University, Changrong Du, Chief Data Officer of Youku Tudou, Yuan Yao from Peking University, Hao Hu from Quanttech, and Jiang Chang from Taiwan National University to a heated discussion about the buzz phrase "big data". The diversity of the speakers led to some refreshing ideas. The second day of the conference consisted of 24 talks in 3 parallel sessions. In each session, talks were grouped by themes. An evening party was held in a café on campus. Conference attendees as well as speakers came for snacks, drinks and exchange of ideas. 

Below is a list of the talks given on May 24th:

1. R packages: principles and best practices, Hadley Wickham (RStudio)
2. How the growth of R helps data-driven organizations succeed, David Smith (Revolution Analytics)
3. Deep Learning Unfolds Big Data Era, Kai Yu, (Baidu Institute of Deep Learning)
4. Hacking Chinese Couplets and Poem with Machine Learning, Ming Zhou (Microsoft Research Asia) 
5. A Statistical Model for Social Network Labeling, Hansheng Wang (Guanghua School of Management, Peking University) 
6. Quantitative Investment in Cloud Computing Era, Hao Hu (W-Quant) 
7. User Analysis in Ad Targeting Process, Zhihui Jin (Tencent) 
8. Establishing a Fund Selection Platform, Yi Zheng (National Sun Yat-sen University, Taiwan) 
9. Handling Three Hundred Million Pieces of Video --- The Application of Data Analysis in Video Industry, Yizhu Liao (Youku Tudou) 

There were three sessions on May 25th:

Session A: 

Data Modeling: 

1. Hacking Models with R, Jiaqi Zhang (Taiwan R User Group)
2. Multi-Cluster Detection, James Wicker (Chinese Academy of Sciences)

Quantitative Investment: 

3. Program Trading Based on R, Liang Jing, (Quant Tech)
4. Blood and Tears in Development, Ice and Fire in Trading, Guanxun Mu (individual investor)
5. Application of R Language in Large Financial Data, Dan Zhang (SupStat)

Data Visualization: 

6. Interactive Visualization with R, Liangbo Wang (Biomedical Electrical Engineering and Computer Science Research Center, National Taiwan University)
7. RECHARTS graphic package, Yang Zhou (AdMaster) 
8. GGVIS Sneak Peek, Hadley Wickham (RStudio)

Session B: 

Big Data Industry: 

1. New Direction of Big Data: New Data Industry In The Trend Of Sharing Data, Yanping Chen (SupStat)
2. R-Web: Big Data Analysis and Consulting Cloud Platform, Jingyang Chen (Tamkang University)

R in Big Data: 

3. Techniques of Breaking the Bottleneck of R’s Inner-storage, Qiang Kou (Southern Statistical Science Research Center)
4. Large Scale Learning with R, Qixuan Wu (Department of Electrical Engineering, National Taiwan University)
5. Big Data Analysis with RHadoop, Youwei Qiu (Numerinfo)

R techniques: 

6. Pipelining in R, Kun Ren (Xiamen University)
7. Developing R in the Context of Research, Ye Zhang (Sun Yat-Sen University) 
8. Eigen Decomposition of Massive Matrices, SVD, NMF in R, Yixuan Qiu (Purdue University)

Session C: 

R with Other Tools: 

1. Data Analysis with R and Python, Weiting Guo (Taiwan R User Group)
2. Combine Microsoft Office with R, Jian Li (Mango Solutions)

Applications of Data Analysis: 

3. Application of Data Analysis in Decision Making of Traditional Business Industry, Hui Lin (DuPont Pioneer)
4. Tiny Beautiful Data Products, He Ouyang (Glamour Sales)
5. R and Data Mining in Enterprise, Sizhe Liu (Jingdong)

R with Biology and Psychology: 

6. Integrated Pipeline for Systems Pharmacology in R/Bioconductor, Nan Xiao (Central South University)
7. Application of R in the Development of New Medicine, Huan Yang (Mango Solutions)
8. Combining R with Psychology: An illustration with SEM, Ge Xiang (University of Notre Dame)

The conference was primarily in Chinese, with exception of the talks by David Smith and Hadley Wickham. Most of the slides are in English. The conference materials, including the abstract booklet, presentation slides and the recording of the panel discussion are available on the website http://china-r.org.

The conference committee consists of Taiyun Wei, Tao Gao, Jing Leng, Zhiji Huo, Miaozhu Li, Nan Xiao, Yihui Xie, Yishuo Deng, Yanping Chen, Yu Chen, Zhenshun Lin, Jian Wang, Hui Lin, Jian Li, Jianchong Su, Zhanhang Xiao, Sen Chen, Yixuan Qiu, Gang Chen, Yibo Chen, Zhiheng Hao, Xiang Zhang, and Liyun Chen. We would love to thank the help from the volunteers coming from universities and institutes all over China, the kind support from the School of Statistics, Renmin University, and the sponsorship from SupStat, Revolution Analytics, RStudio, VSNC, 1degreenorth, Huazhang Publishing, and Springer. We are looking forward to meeting more enthusiastic R users at the next R conference in Shanghai later this year!
